-- 코드를 입력하세요
--  저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여, 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 리스트를 출력하는 SQL문을 작성해주세요.
SELECT B.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY,SUM(BS.SALES * B.PRICE) AS TOTAL_SALES FROM BOOK B INNER JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID 
WHERE MONTH(SALES_DATE) = 1 
GROUP BY A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC