-- 코드를 입력하세요
SELECT R1.FOOD_TYPE,R1.REST_ID,R1.REST_NAME,R1.FAVORITES FROM REST_INFO AS R1, (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) AS R2 WHERE R2.FOOD_TYPE = R1.FOOD_TYPE AND R1.FAVORITES = R2.FAVORITES ORDER BY FOOD_TYPE DESC


-- TABLE2
