-- 서울에 위치한 식당들의 식당 ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수
# select REST_ID, REST_NAME, FOOD_TYPE, VIEWS, FAVORITES, PARKING_LOT, ADDRESS from rest_info where address like('서울특별시%')
# select REVIEW_ID, rest_info.REST_ID, MEMBER_ID, REVIEW_SCORE, REVIEW_TEXT,REVIEW_DATE from rest_review LEFT JOIN REST_INFO 
# on rest_info.rest_id = rest_review.rest_id 
# WHERE REST_INFO.ADDRESS LIKE('서울특별시%')
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE,I.FAVORITES,I.ADDRESS,ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE FROM REST_INFO I INNER JOIN REST_REVIEW R
ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE('서울%')
GROUP BY I.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC