SELECT E.ID,
    CASE
        WHEN E.SIZE_OF_COLONY <= 100
        THEN 'LOW'
        WHEN E.SIZE_OF_COLONY > 100 AND E.SIZE_OF_COLONY <= 1000
        THEN 'MEDIUM'
        ELSE 'HIGH'
    END SIZE
FROM ECOLI_DATA E
ORDER BY 1;