-- 코드를 입력하세요
SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS USING(CAR_ID)
WHERE C.CAR_TYPE = '세단'
AND HIS.START_DATE LIKE '2022-10-%'
ORDER BY 1 DESC