-- 2022년 10월 5일에 등록
-- 거래상태가 SALE 이면 판매중, RESERVED이면 예약중, DONE이면 거래완료 분류하여 출력
SELECT BOARD_ID,WRITER_ID,TITLE,PRICE,
CASE 
    WHEN STATUS LIKE 'DONE' THEN '거래완료'
    WHEN STATUS LIKE 'SALE' THEN '판매중'
    ELSE '예약중'
END AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE LIKE '2022-10-05'
ORDER BY 1 DESC