-- 조회수 가장 높은 게시물에 대한 첨부파일 경로 FILE ID 내림 
SELECT CONCAT("/home/grep/src/",F.BOARD_ID,'/',F.FILE_ID,F.FILE_NAME,F.FILE_EXT) FILE_PATH FROM USED_GOODS_FILE F JOIN USED_GOODS_BOARD B USING(BOARD_ID)
WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY 1 DESC;